use serde::{Deserialize, Serialize};

pub const PLAN_SCHEMA_VERSION: u32 = 2;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub enum AccountType {
    Taxable,
    Traditional,
    Roth,
    #[serde(rename = "HSA")]
    Hsa,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum FilingStatus {
    Single,
    MarriedFilingJointly,
    MarriedFilingSeparately,
    HeadOfHousehold,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "UPPERCASE")]
pub enum State {
    CA,
    TX,
    FL,
    NY,
    WA,
    #[serde(rename = "Other")]
    Other,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AssetWeights {
    pub stocks: f64,
    pub bonds: f64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Account {
    #[serde(rename = "type")]
    pub account_type: AccountType,
    pub balance: f64,
    #[serde(rename = "assetWeights")]
    pub asset_weights: AssetWeights,
    /** Internal cash generated by forced distributions; never part of the wire format. */
    #[serde(skip)]
    pub is_surplus_cash: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UserProfile {
    pub age: u32,
    #[serde(rename = "birthYear")]
    pub birth_year: i32,
    pub state: State,
    #[serde(rename = "filingStatus")]
    pub filing_status: FilingStatus,
    #[serde(rename = "retirementAge")]
    pub retirement_age: u32,
    #[serde(rename = "currentSalary")]
    pub current_salary: f64,
    #[serde(rename = "salaryGrowthRate")]
    pub salary_growth_rate: f64,
    #[serde(rename = "currentSpending")]
    pub current_spending: f64,
    #[serde(rename = "workingSpendingGrowthRate", default)]
    pub working_spending_growth_rate: f64,
    #[serde(rename = "retirementSpending", alias = "desiredSpending")]
    pub retirement_spending: f64,
    #[serde(rename = "retirementSpendingGrowthRate", alias = "spendingGrowthRate")]
    pub retirement_spending_growth_rate: f64,
    #[serde(rename = "lifeExpectancy")]
    pub life_expectancy: u32,
    #[serde(rename = "asOfDate")]
    pub as_of_date: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SocialSecuritySettings {
    pub enabled: bool,
    #[serde(rename = "estimatedBenefit")]
    pub estimated_benefit: Option<f64>,
    #[serde(rename = "claimAge")]
    pub claim_age: u32,
    #[serde(rename = "manualOverride")]
    pub manual_override: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum SimulationModel {
    #[serde(rename = "historical")]
    Historical,
    #[serde(rename = "parametric")]
    Parametric,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AnnualContributions {
    pub hsa: f64,
    pub traditional: f64,
    pub roth: f64,
    pub taxable: f64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProjectionSettings {
    #[serde(rename = "simulationModel")]
    pub simulation_model: SimulationModel,
    #[serde(rename = "randomSeed")]
    pub random_seed: Option<u64>,
    #[serde(rename = "taxableGainRatio")]
    pub taxable_gain_ratio: f64,
    /// HDHP coverage. Without it there is no HSA contribution to deduct.
    #[serde(rename = "hsaEligible", default)]
    pub hsa_eligible: bool,
    /// Without a backdoor conversion, a Roth IRA contribution is not modeled.
    #[serde(rename = "useBackdoorRoth", default)]
    pub use_backdoor_roth: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RetirementPlan {
    #[serde(rename = "schemaVersion", default)]
    pub schema_version: u32,
    pub profile: UserProfile,
    pub accounts: Vec<Account>,
    #[serde(rename = "socialSecurity")]
    pub social_security: SocialSecuritySettings,
    pub assumptions: ProjectionSettings,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PathProjection {
    pub year: u32,
    pub age: u32,
    #[serde(rename = "portfolioValue")]
    pub portfolio_value: f64,
    pub income: f64,
    pub spending: f64,
    pub taxes: f64,
    pub savings: f64,
    #[serde(rename = "socialSecurityBenefit")]
    pub social_security_benefit: f64,
    #[serde(rename = "isRetired")]
    pub is_retired: bool,
    #[serde(rename = "withdrawalTaxable")]
    pub withdrawal_taxable: f64,
    #[serde(rename = "withdrawalTraditional")]
    pub withdrawal_traditional: f64,
    #[serde(rename = "withdrawalRoth")]
    pub withdrawal_roth: f64,
    #[serde(rename = "rmdAmount")]
    pub rmd_amount: f64,
    #[serde(rename = "depositTaxable")]
    pub deposit_taxable: f64,
    #[serde(rename = "depositTraditional")]
    pub deposit_traditional: f64,
    #[serde(rename = "depositRoth")]
    pub deposit_roth: f64,
    #[serde(rename = "depositHSA")]
    pub deposit_hsa: f64,
    #[serde(rename = "withdrawalHSA")]
    pub withdrawal_hsa: f64,
    #[serde(rename = "insufficientFunds")]
    pub insufficient_funds: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PathResult {
    #[serde(rename = "terminalWealth")]
    pub terminal_wealth: f64,
    pub projections: Vec<PathProjection>,
    pub success: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct YearlyProjection {
    #[serde(flatten)]
    pub base: PathProjection,
    pub p5: f64,
    pub p10: f64,
    pub p15: f64,
    pub p25: f64,
    pub p50: f64,
    pub p75: f64,
    pub p90: f64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IncomeSourcesRow {
    pub age: u32,
    #[serde(rename = "isRetired")]
    pub is_retired: bool,
    #[serde(rename = "socialSecurityBenefit")]
    pub social_security_benefit: f64,
    #[serde(rename = "withdrawalTaxable")]
    pub withdrawal_taxable: f64,
    #[serde(rename = "withdrawalTraditional")]
    pub withdrawal_traditional: f64,
    #[serde(rename = "withdrawalRoth")]
    pub withdrawal_roth: f64,
    #[serde(rename = "withdrawalHSA")]
    pub withdrawal_hsa: f64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SimulationResult {
    /// Fraction of paths that fully fund every modeled working and retirement year.
    #[serde(rename = "successProbability")]
    pub success_probability: f64,
    #[serde(rename = "medianTerminalWealth")]
    pub median_terminal_wealth: f64,
    #[serde(rename = "percentile5TerminalWealth")]
    pub percentile5_terminal_wealth: f64,
    #[serde(rename = "percentile10TerminalWealth")]
    pub percentile10_terminal_wealth: f64,
    #[serde(rename = "percentile90TerminalWealth")]
    pub percentile90_terminal_wealth: f64,
    #[serde(rename = "yearlyProjections")]
    pub yearly_projections: Vec<YearlyProjection>,
    /// 1 - success_probability. A path fails when any modeled year is underfunded.
    #[serde(rename = "riskOfRuin")]
    pub risk_of_ruin: f64,
    #[serde(
        rename = "incomeSourcesPath",
        skip_serializing_if = "Vec::is_empty",
        default
    )]
    pub income_sources_path: Vec<IncomeSourcesRow>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MCConfig {
    pub paths: u32,
    pub seed: u64,
    /// When Historical mode, true → block bootstrap, false → single-year bootstrap.
    /// Defaults to true to match MONTE_CARLO_DEFAULTS.use_historical_bootstrap.
    #[serde(
        rename = "useHistoricalBootstrap",
        default = "default_use_historical_bootstrap"
    )]
    pub use_historical_bootstrap: bool,
    #[serde(rename = "blockSize", default = "default_block_size")]
    pub block_size: usize,
}

fn default_use_historical_bootstrap() -> bool {
    true
}
fn default_block_size() -> usize {
    3
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SimulationRequest {
    pub plan: RetirementPlan,
    pub config: MCConfig,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BatchSimulationRequest {
    pub id: String,
    pub plan: RetirementPlan,
    pub config: MCConfig,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BatchSimulationResponse {
    pub id: String,
    pub result: SimulationResult,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BatchRequest {
    pub simulations: Vec<BatchSimulationRequest>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BatchResponse {
    pub results: Vec<BatchSimulationResponse>,
}

#[cfg(test)]
mod tests {
    use super::State;

    #[test]
    fn other_state_matches_typescript_wire_value() {
        let state: State = serde_json::from_str("\"Other\"").unwrap();
        assert!(matches!(state, State::Other));
    }
}
