use serde::{Deserialize, Serialize};

pub const PLAN_SCHEMA_VERSION: u32 = 8;
pub const WASM_ABI_VERSION: u32 = 1;

/// Medicare eligibility, which is where retirement premiums step down.
pub const MEDICARE_AGE: u32 = 65;

/// Version that introduced phase-based spending. Older requests carry a flat
/// working amount and compound retirement growth from the as-of year. Gating
/// on this rather than on the current version is what keeps the next schema
/// bump from reverting the previous version to that older math.
pub const PHASE_SPENDING_SCHEMA_VERSION: u32 = 2;

/// Version that reworked retirement healthcare. Older requests compounded real
/// growth from the first retirement year rather than the as-of date, and paid
/// the entered premium whatever the household's income, with no marketplace
/// credit before Medicare and no IRMAA surcharge after it.
pub const HEALTHCARE_MODEL_SCHEMA_VERSION: u32 = 5;

/// Version that stopped pricing the first retirement year on a salary the
/// household no longer earns. Older requests test the marketplace credit
/// against a prior-year MAGI that still counts the final paycheck, so a
/// household retiring at 58 is charged the full list premium on the strength
/// of its age-57 income. Gating on this rather than on the current version is
/// what keeps the next schema bump from reverting to that.
pub const RETIREMENT_MAGI_ESTIMATE_SCHEMA_VERSION: u32 = 8;

/// Version that introduced the long-term-care episode. Older requests priced no
/// care at all, so gating on this keeps a bundle built before the model from
/// having a cost it never asked for charged against its plan.
pub const LTC_MODEL_SCHEMA_VERSION: u32 = 7;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub enum AccountType {
    Taxable,
    Traditional,
    Roth,
    #[serde(rename = "HSA")]
    Hsa,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum FilingStatus {
    Single,
    MarriedFilingJointly,
    MarriedFilingSeparately,
    HeadOfHousehold,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "UPPERCASE")]
pub enum State {
    CA,
    TX,
    FL,
    NY,
    WA,
    #[serde(rename = "Other")]
    Other,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AssetWeights {
    pub stocks: f64,
    pub bonds: f64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Account {
    #[serde(rename = "type")]
    pub account_type: AccountType,
    pub balance: f64,
    #[serde(rename = "assetWeights")]
    pub asset_weights: AssetWeights,
    /// Internal cash generated by forced distributions; never part of the wire format.
    #[serde(skip)]
    pub is_surplus_cash: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UserProfile {
    /// Date of birth, ISO. Age and the RMD / Social Security birth-year cohort
    /// are both derived from it, so they can never disagree.
    #[serde(rename = "birthDate")]
    pub birth_date: String,
    pub state: State,
    #[serde(rename = "filingStatus")]
    pub filing_status: FilingStatus,
    #[serde(rename = "retirementAge")]
    pub retirement_age: u32,
    #[serde(rename = "currentSalary")]
    pub current_salary: f64,
    #[serde(rename = "salaryGrowthRate")]
    pub salary_growth_rate: f64,
    #[serde(rename = "currentSpending")]
    pub current_spending: f64,
    #[serde(rename = "workingSpendingGrowthRate", default)]
    pub working_spending_growth_rate: f64,
    #[serde(rename = "retirementSpending", alias = "desiredSpending")]
    pub retirement_spending: f64,
    #[serde(rename = "retirementSpendingGrowthRate", alias = "spendingGrowthRate")]
    pub retirement_spending_growth_rate: f64,
    #[serde(rename = "lifeExpectancy")]
    pub life_expectancy: u32,
    /// Healthcare in retirement, carried separately from `current_spending`
    /// because it steps down at Medicare and grows faster than everything else.
    #[serde(rename = "retirementHealthcare", default)]
    pub retirement_healthcare: RetirementHealthcare,
    /// Long-term care, drawn per path rather than budgeted, so it is a
    /// distribution rather than an annual amount.
    #[serde(rename = "longTermCare", default)]
    pub long_term_care: LongTermCare,
    #[serde(rename = "asOfDate")]
    pub as_of_date: String,
}

/// Retirement healthcare, which is a step at Medicare eligibility rather than a
/// share of spending. Premiums and out-of-pocket costs are separate because
/// Medicare, and later any subsidy or surcharge, moves only the premium.
///
/// All figures are household totals in real dollars. A request that predates
/// this field gets zeros, which reproduces the projection it would have had.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct RetirementHealthcare {
    #[serde(rename = "preMedicarePremium", default)]
    pub pre_medicare_premium: f64,
    #[serde(rename = "medicarePremium", default)]
    pub medicare_premium: f64,
    #[serde(rename = "outOfPocket", default)]
    pub out_of_pocket: f64,
    #[serde(rename = "realGrowthRate", default)]
    pub real_growth_rate: f64,
}

/// Long-term care, whose cost is a lifetime out-of-pocket draw rather than an
/// annual budget line. `cost_multiplier` scales the drawn amount for location
/// and care level; income is already carried by the distribution itself.
///
/// Unlike the healthcare fields, an absent value is not a no-op: the model is
/// on for every plan, including requests that predate it.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LongTermCare {
    #[serde(rename = "enabled", default = "default_ltc_enabled")]
    pub enabled: bool,
    #[serde(rename = "costMultiplier", default = "default_ltc_cost_multiplier")]
    pub cost_multiplier: f64,
}

impl Default for LongTermCare {
    fn default() -> Self {
        Self {
            enabled: default_ltc_enabled(),
            cost_multiplier: default_ltc_cost_multiplier(),
        }
    }
}

fn default_ltc_enabled() -> bool {
    true
}

fn default_ltc_cost_multiplier() -> f64 {
    1.0
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SocialSecuritySettings {
    pub enabled: bool,
    #[serde(rename = "estimatedBenefit")]
    pub estimated_benefit: Option<f64>,
    #[serde(rename = "claimAge")]
    pub claim_age: u32,
    #[serde(rename = "manualOverride")]
    pub manual_override: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum SimulationModel {
    #[serde(rename = "historical")]
    Historical,
    #[serde(rename = "parametric")]
    Parametric,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AnnualContributions {
    pub hsa: f64,
    pub traditional: f64,
    pub roth: f64,
    pub taxable: f64,
}

/// How much ordinary income a conversion year may reach. Bracket ceilings cap
/// taxable income at the named bracket's top; `IrmaaTier` caps MAGI below the
/// first Medicare surcharge tier instead.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum RothConversionCeiling {
    #[serde(rename = "bracket12")]
    Bracket12,
    #[serde(rename = "bracket22")]
    Bracket22,
    #[serde(rename = "bracket24")]
    Bracket24,
    #[serde(rename = "bracket32")]
    Bracket32,
    #[serde(rename = "irmaaTier")]
    IrmaaTier,
}

/// Conversions run from retirement through the year before RMDs begin, so both
/// ends of the window are derived and only the policy is carried.
#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
pub struct RothConversionPolicy {
    #[serde(default)]
    pub enabled: bool,
    #[serde(default = "default_conversion_ceiling")]
    pub ceiling: RothConversionCeiling,
}

impl Default for RothConversionPolicy {
    fn default() -> Self {
        Self {
            enabled: false,
            ceiling: default_conversion_ceiling(),
        }
    }
}

fn default_conversion_ceiling() -> RothConversionCeiling {
    RothConversionCeiling::Bracket24
}

/// Rate applied to the Traditional and HSA balances left at the horizon, to
/// report terminal wealth after the tax nobody has paid yet.
fn default_terminal_tax_rate() -> f64 {
    0.30
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProjectionSettings {
    #[serde(rename = "simulationModel")]
    pub simulation_model: SimulationModel,
    #[serde(rename = "randomSeed", default = "default_random_seed")]
    pub random_seed: u32,
    #[serde(rename = "taxableGainRatio")]
    pub taxable_gain_ratio: f64,
    /// HDHP coverage. Without it there is no HSA contribution to deduct.
    #[serde(rename = "hsaEligible", default)]
    pub hsa_eligible: bool,
    /// Without a backdoor conversion, a Roth IRA contribution is not modeled.
    #[serde(rename = "useBackdoorRoth", default)]
    pub use_backdoor_roth: bool,
    /// Absent from plans saved before conversions existed, where the default
    /// leaves them off — which is the behavior those plans were built against.
    #[serde(rename = "rothConversion", default)]
    pub roth_conversion: RothConversionPolicy,
    /// Hold a year's ordinary income under the threshold the household's next
    /// marketplace credit or Medicare surcharge is tested against, drawing Roth
    /// for the rest. Absent from plans saved before the setting existed, where
    /// the default leaves the plain order in place.
    #[serde(rename = "magiAwareWithdrawals", default)]
    pub magi_aware_withdrawals: bool,
    #[serde(rename = "terminalTaxRate", default = "default_terminal_tax_rate")]
    pub terminal_tax_rate: f64,
}

fn default_random_seed() -> u32 {
    42
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RetirementPlan {
    #[serde(rename = "schemaVersion", default)]
    pub schema_version: u32,
    pub profile: UserProfile,
    pub accounts: Vec<Account>,
    #[serde(rename = "socialSecurity")]
    pub social_security: SocialSecuritySettings,
    pub assumptions: ProjectionSettings,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PathProjection {
    pub year: u32,
    pub age: u32,
    #[serde(rename = "portfolioValue")]
    pub portfolio_value: f64,
    pub income: f64,
    pub spending: f64,
    pub taxes: f64,
    pub savings: f64,
    #[serde(rename = "socialSecurityBenefit")]
    pub social_security_benefit: f64,
    #[serde(rename = "isRetired")]
    pub is_retired: bool,
    #[serde(rename = "withdrawalTaxable")]
    pub withdrawal_taxable: f64,
    #[serde(rename = "withdrawalTraditional")]
    pub withdrawal_traditional: f64,
    #[serde(rename = "withdrawalRoth")]
    pub withdrawal_roth: f64,
    #[serde(rename = "rmdAmount")]
    pub rmd_amount: f64,
    /// Pre-tax dollars moved Traditional -> Roth this year. An internal
    /// transfer, so it is no part of `spending` or the withdrawal totals; only
    /// the tax it adds reaches `taxes`.
    #[serde(rename = "rothConversion", default)]
    pub roth_conversion: f64,
    #[serde(rename = "depositTaxable")]
    pub deposit_taxable: f64,
    #[serde(rename = "depositTraditional")]
    pub deposit_traditional: f64,
    #[serde(rename = "depositRoth")]
    pub deposit_roth: f64,
    #[serde(rename = "depositHSA")]
    pub deposit_hsa: f64,
    #[serde(rename = "withdrawalHSA")]
    pub withdrawal_hsa: f64,
    /// Funded recurring retirement healthcare for the year, excluding any
    /// long-term-care episode. Part of the same `spending` total and zero while
    /// working, where healthcare sits inside `current_spending`.
    #[serde(rename = "healthcareCost")]
    pub healthcare_cost: f64,
    /// Funded long-term-care spending for the year, reported separately from
    /// recurring healthcare while remaining part of `spending`.
    #[serde(rename = "longTermCareCost", default)]
    pub long_term_care_cost: f64,
    #[serde(rename = "insufficientFunds")]
    pub insufficient_funds: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PathResult {
    #[serde(rename = "terminalWealth")]
    pub terminal_wealth: f64,
    /// Terminal wealth net of the tax still owed on Traditional and HSA.
    #[serde(rename = "afterTaxTerminalWealth", default)]
    pub after_tax_terminal_wealth: f64,
    pub projections: Vec<PathProjection>,
    pub success: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct YearlyProjection {
    #[serde(flatten)]
    pub base: PathProjection,
    pub p5: f64,
    pub p10: f64,
    pub p15: f64,
    pub p25: f64,
    pub p50: f64,
    pub p75: f64,
    pub p90: f64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OutcomeCashFlowRow {
    pub age: u32,
    #[serde(rename = "isRetired")]
    pub is_retired: bool,
    pub income: f64,
    pub spending: f64,
    pub taxes: f64,
    pub savings: f64,
    #[serde(rename = "socialSecurityBenefit")]
    pub social_security_benefit: f64,
    #[serde(rename = "withdrawalTaxable")]
    pub withdrawal_taxable: f64,
    #[serde(rename = "withdrawalTraditional")]
    pub withdrawal_traditional: f64,
    #[serde(rename = "withdrawalRoth")]
    pub withdrawal_roth: f64,
    #[serde(rename = "withdrawalHSA")]
    pub withdrawal_hsa: f64,
    #[serde(rename = "healthcareCost")]
    pub healthcare_cost: f64,
    #[serde(rename = "longTermCareCost", default)]
    pub long_term_care_cost: f64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OutcomeBucket {
    #[serde(rename = "centerPercentile")]
    pub center_percentile: u32,
    #[serde(rename = "lowerPercentile")]
    pub lower_percentile: u32,
    #[serde(rename = "upperPercentile")]
    pub upper_percentile: u32,
    #[serde(rename = "successProbability")]
    pub success_probability: f64,
    pub projections: Vec<OutcomeCashFlowRow>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SimulationResult {
    /// Fraction of paths that fully fund every modeled working and retirement year.
    #[serde(rename = "successProbability")]
    pub success_probability: f64,
    /// The median path's terminal wealth net of the tax owed on its Traditional
    /// and HSA balances. Reported beside the gross figure, not in place of it.
    #[serde(rename = "medianAfterTaxTerminalWealth", default)]
    pub median_after_tax_terminal_wealth: f64,
    #[serde(rename = "medianTerminalWealth")]
    pub median_terminal_wealth: f64,
    #[serde(rename = "percentile5TerminalWealth")]
    pub percentile5_terminal_wealth: f64,
    #[serde(rename = "percentile10TerminalWealth")]
    pub percentile10_terminal_wealth: f64,
    #[serde(rename = "percentile90TerminalWealth")]
    pub percentile90_terminal_wealth: f64,
    #[serde(rename = "yearlyProjections")]
    pub yearly_projections: Vec<YearlyProjection>,
    /// 1 - success_probability. A path fails when any modeled year is underfunded.
    #[serde(rename = "riskOfRuin")]
    pub risk_of_ruin: f64,
    #[serde(
        rename = "outcomeBuckets",
        skip_serializing_if = "Vec::is_empty",
        default
    )]
    pub outcome_buckets: Vec<OutcomeBucket>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MCConfig {
    pub paths: u32,
    pub seed: u32,
    /// In historical mode, true selects block bootstrap and false selects
    /// single-year bootstrap. Older requests default to block bootstrap.
    #[serde(
        rename = "useHistoricalBootstrap",
        default = "default_use_historical_bootstrap"
    )]
    pub use_historical_bootstrap: bool,
    #[serde(rename = "blockSize", default = "default_block_size")]
    pub block_size: usize,
}

fn default_use_historical_bootstrap() -> bool {
    true
}
fn default_block_size() -> usize {
    5
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SimulationRequest {
    pub plan: RetirementPlan,
    pub config: MCConfig,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BatchSimulationRequest {
    pub id: String,
    pub plan: RetirementPlan,
    pub config: MCConfig,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BatchSimulationResponse {
    pub id: String,
    pub result: SimulationResult,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BatchSimulationSummaryResponse {
    pub id: String,
    #[serde(rename = "successProbability")]
    pub success_probability: f64,
}

#[derive(Debug, Clone, Copy, Default, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub enum BatchResponseMode {
    #[default]
    Full,
    Summary,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BatchRequest {
    #[serde(rename = "responseMode", default)]
    pub response_mode: BatchResponseMode,
    pub simulations: Vec<BatchSimulationRequest>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BatchResponse {
    pub results: Vec<BatchSimulationResponse>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BatchSummaryResponse {
    pub results: Vec<BatchSimulationSummaryResponse>,
}

#[cfg(test)]
mod tests {
    use super::{BatchRequest, BatchResponseMode, RetirementPlan, State};

    #[test]
    fn other_state_matches_public_wire_value() {
        let state: State = serde_json::from_str("\"Other\"").unwrap();
        assert!(matches!(state, State::Other));
    }

    #[test]
    fn legacy_plan_without_seed_defaults_to_42() {
        let plan: RetirementPlan = serde_json::from_value(serde_json::json!({
            "schemaVersion": 3,
            "profile": {
                "birthDate": "1966-01-01",
                "state": "TX",
                "filingStatus": "Single",
                "retirementAge": 65,
                "currentSalary": 100000.0,
                "salaryGrowthRate": 0.01,
                "currentSpending": 60000.0,
                "retirementSpending": 60000.0,
                "retirementSpendingGrowthRate": 0.0,
                "lifeExpectancy": 80,
                "asOfDate": "2026-01-01"
            },
            "accounts": [],
            "socialSecurity": {
                "enabled": true,
                "estimatedBenefit": null,
                "claimAge": 67,
                "manualOverride": false
            },
            "assumptions": {
                "simulationModel": "historical",
                "taxableGainRatio": 0.5,
                "hsaEligible": false,
                "useBackdoorRoth": false
            }
        }))
        .unwrap();

        assert_eq!(plan.assumptions.random_seed, 42);
    }

    #[test]
    fn plan_without_long_term_care_defaults_to_the_model_being_on() {
        let plan: RetirementPlan = serde_json::from_value(serde_json::json!({
            "schemaVersion": 6,
            "profile": {
                "birthDate": "1966-01-01",
                "state": "TX",
                "filingStatus": "Single",
                "retirementAge": 65,
                "currentSalary": 100000.0,
                "salaryGrowthRate": 0.01,
                "currentSpending": 60000.0,
                "retirementSpending": 60000.0,
                "retirementSpendingGrowthRate": 0.0,
                "lifeExpectancy": 80,
                "asOfDate": "2026-01-01"
            },
            "accounts": [],
            "socialSecurity": {
                "enabled": true,
                "estimatedBenefit": null,
                "claimAge": 67,
                "manualOverride": false
            },
            "assumptions": {
                "simulationModel": "historical",
                "taxableGainRatio": 0.5,
                "hsaEligible": false,
                "useBackdoorRoth": false
            }
        }))
        .unwrap();

        assert!(plan.profile.long_term_care.enabled);
        assert_eq!(plan.profile.long_term_care.cost_multiplier, 1.0);
    }

    #[test]
    fn batch_response_mode_defaults_to_legacy_full() {
        let request: BatchRequest = serde_json::from_value(serde_json::json!({
            "simulations": []
        }))
        .unwrap();

        assert_eq!(request.response_mode, BatchResponseMode::Full);
    }
}
